#!/bin/bash

. ./.env

MAX_RETRY=10
DELAY=10

retry () {
    COUNT=${MAX_RETRY}
    echo "[TRY] $@"
    "$@"
    RESULT=$?
    while [ $RESULT -ne 0 ]; do
        if [ $COUNT -le 0 ]; then
            break
        fi
        COUNT=$(($COUNT - 1))
        sleep $DELAY
        echo "[RETRY] $@"
        "$@"
        RESULT=$?
    done
    if [ $RESULT -eq 0 ]; then
        echo "[SUCCESS] $@"
    else
        echo "[FAILED] $@"
    fi
    return $RESULT
}

docker compose up -d squid && sleep 3

distros=("rocky/8" "rocky/9" "ubuntu/22" "ubuntu/24")
pg_vers=(14 15 16 17 18)

for distro in "${distros[@]}"; do
    tag_name=${distro//\//}  # 슬래시(/) 제거
    retry docker build --secret id=git_credentials,src="${HOME}/.git-credentials" \
        --secret id=ssh_privkey,src="${HOME}/.ssh/id_ed25519" \
        --secret id=ssh_pubkey,src="${HOME}/.ssh/id_ed25519.pub" \
        --secret id=ssh_authkeys,src="${HOME}/.ssh/authorized_keys" \
        --add-host host.docker.internal:host-gateway \
        --build-arg ATELIER_SQUID_PORT="${ATELIER_SQUID_PORT}" \
        -t ${tag_name}-init \
        -f dockerfiles/${distro}/Dockerfile-init dockerfiles
    for ver in "${pg_vers[@]}"; do
        retry docker build --secret id=git_credentials,src="${HOME}/.git-credentials" \
            --secret id=ssh_privkey,src="${HOME}/.ssh/id_ed25519" \
            --secret id=ssh_pubkey,src="${HOME}/.ssh/id_ed25519.pub" \
            --secret id=ssh_authkeys,src="${HOME}/.ssh/authorized_keys" \
            --add-host host.docker.internal:host-gateway \
            --build-arg ATELIER_SQUID_PORT="${ATELIER_SQUID_PORT}" \
            --build-arg PG_MAJOR=${ver} \
            -t ${tag_name}-pg${ver} \
            -f dockerfiles/${distro}/Dockerfile-pgxx dockerfiles
    done
done
