services:
  rocky8-init:
    image: rocky8-init
    container_name: rocky8-init
    hostname: rocky8-init
    domainname: atelier
    privileged: true
    tty: false
    extra_hosts:
      - host.docker.internal:host-gateway
      - host:host-gateway
      - init:${ATELIER_SUBNET}.8.1
      - active:${ATELIER_SUBNET}.8.14
      - standby:${ATELIER_SUBNET}.8.44
      - standalone:${ATELIER_SUBNET}.8.74
    networks:
      default:
        ipv4_address: ${ATELIER_SUBNET}.8.1
  rocky8-pg14-active:
    image: rocky8-pg14
    container_name: rocky8-pg14-active
    hostname: rocky8-pg14-active
    domainname: atelier
    privileged: true
    tty: false
    extra_hosts:
      - host.docker.internal:host-gateway
      - host:host-gateway
      - init:${ATELIER_SUBNET}.8.1
      - active:${ATELIER_SUBNET}.8.14
      - standby:${ATELIER_SUBNET}.8.44
      - standalone:${ATELIER_SUBNET}.8.74
    networks:
      default:
        ipv4_address: ${ATELIER_SUBNET}.8.14
    volumes:
      - rocky8-pg14-active-vscode-server:/var/lib/pgsql/.vscode-server
      - rocky8-pg14-active-workspace:/var/lib/pgsql/workspace
  rocky8-pg14-standby:
    image: rocky8-pg14
    container_name: rocky8-pg14-standby
    hostname: rocky8-pg14-standby
    domainname: atelier
    privileged: true
    tty: false
    extra_hosts:
      - host.docker.internal:host-gateway
      - host:host-gateway
      - init:${ATELIER_SUBNET}.8.1
      - active:${ATELIER_SUBNET}.8.14
      - standby:${ATELIER_SUBNET}.8.44
      - standalone:${ATELIER_SUBNET}.8.74
    networks:
      default:
        ipv4_address: ${ATELIER_SUBNET}.8.44
    volumes:
      - rocky8-pg14-standby-vscode-server:/var/lib/pgsql/.vscode-server
      - rocky8-pg14-standby-workspace:/var/lib/pgsql/workspace
  rocky8-pg14-standalone:
    image: rocky8-pg14
    container_name: rocky8-pg14-standalone
    hostname: rocky8-pg14-standalone
    domainname: atelier
    privileged: true
    tty: false
    extra_hosts:
      - host.docker.internal:host-gateway
      - host:host-gateway
      - init:${ATELIER_SUBNET}.8.1
      - active:${ATELIER_SUBNET}.8.14
      - standby:${ATELIER_SUBNET}.8.44
      - standalone:${ATELIER_SUBNET}.8.74
    networks:
      default:
        ipv4_address: ${ATELIER_SUBNET}.8.74
    volumes:
      - rocky8-pg14-standalone-vscode-server:/var/lib/pgsql/.vscode-server
      - rocky8-pg14-standalone-workspace:/var/lib/pgsql/workspace
  rocky9-init:
    image: rocky9-init
    container_name: rocky9-init
    hostname: rocky9-init
    domainname: atelier
    privileged: true
    tty: false
    extra_hosts:
      - host.docker.internal:host-gateway
      - host:host-gateway
      - init:${ATELIER_SUBNET}.9.1
      - active:${ATELIER_SUBNET}.9.14
      - standby:${ATELIER_SUBNET}.9.44
      - standalone:${ATELIER_SUBNET}.9.74
    networks:
      default:
        ipv4_address: ${ATELIER_SUBNET}.9.1
  rocky9-pg14-active:
    image: rocky9-pg14
    container_name: rocky9-pg14-active
    hostname: rocky9-pg14-active
    domainname: atelier
    privileged: true
    tty: false
    extra_hosts:
      - host.docker.internal:host-gateway
      - host:host-gateway
      - init:${ATELIER_SUBNET}.9.1
      - active:${ATELIER_SUBNET}.9.14
      - standby:${ATELIER_SUBNET}.9.44
      - standalone:${ATELIER_SUBNET}.9.74
    networks:
      default:
        ipv4_address: ${ATELIER_SUBNET}.9.14
    volumes:
      - rocky9-pg14-active-vscode-server:/var/lib/pgsql/.vscode-server
      - rocky9-pg14-active-workspace:/var/lib/pgsql/workspace
  rocky9-pg14-standby:
    image: rocky9-pg14
    container_name: rocky9-pg14-standby
    hostname: rocky9-pg14-standby
    domainname: atelier
    privileged: true
    tty: false
    extra_hosts:
      - host.docker.internal:host-gateway
      - host:host-gateway
      - init:${ATELIER_SUBNET}.9.1
      - active:${ATELIER_SUBNET}.9.14
      - standby:${ATELIER_SUBNET}.9.44
      - standalone:${ATELIER_SUBNET}.9.74
    networks:
      default:
        ipv4_address: ${ATELIER_SUBNET}.9.44
    volumes:
      - rocky9-pg14-standby-vscode-server:/var/lib/pgsql/.vscode-server
      - rocky9-pg14-standby-workspace:/var/lib/pgsql/workspace
  rocky9-pg14-standalone:
    image: rocky9-pg14
    container_name: rocky9-pg14-standalone
    hostname: rocky9-pg14-standalone
    domainname: atelier
    privileged: true
    tty: false
    extra_hosts:
      - host.docker.internal:host-gateway
      - host:host-gateway
      - init:${ATELIER_SUBNET}.9.1
      - active:${ATELIER_SUBNET}.9.14
      - standby:${ATELIER_SUBNET}.9.44
      - standalone:${ATELIER_SUBNET}.9.74
    networks:
      default:
        ipv4_address: ${ATELIER_SUBNET}.9.74
    volumes:
      - rocky9-pg14-standalone-vscode-server:/var/lib/pgsql/.vscode-server
      - rocky9-pg14-standalone-workspace:/var/lib/pgsql/workspace
  ubuntu22-init:
    image: ubuntu22-init
    container_name: ubuntu22-init
    hostname: ubuntu22-init
    domainname: atelier
    privileged: true
    tty: false
    extra_hosts:
      - host.docker.internal:host-gateway
      - host:host-gateway
      - init:${ATELIER_SUBNET}.22.1
      - active:${ATELIER_SUBNET}.22.14
      - standby:${ATELIER_SUBNET}.22.44
      - standalone:${ATELIER_SUBNET}.22.74
    networks:
      default:
        ipv4_address: ${ATELIER_SUBNET}.22.1
  ubuntu22-pg14-active:
    image: ubuntu22-pg14
    container_name: ubuntu22-pg14-active
    hostname: ubuntu22-pg14-active
    domainname: atelier
    privileged: true
    tty: false
    extra_hosts:
      - host.docker.internal:host-gateway
      - host:host-gateway
      - init:${ATELIER_SUBNET}.22.1
      - active:${ATELIER_SUBNET}.22.14
      - standby:${ATELIER_SUBNET}.22.44
      - standalone:${ATELIER_SUBNET}.22.74
    networks:
      default:
        ipv4_address: ${ATELIER_SUBNET}.22.14
    volumes:
      - ubuntu22-pg14-active-vscode-server:/var/lib/postgresql/.vscode-server
      - ubuntu22-pg14-active-workspace:/var/lib/postgresql/workspace
  ubuntu22-pg14-standby:
    image: ubuntu22-pg14
    container_name: ubuntu22-pg14-standby
    hostname: ubuntu22-pg14-standby
    domainname: atelier
    privileged: true
    tty: false
    extra_hosts:
      - host.docker.internal:host-gateway
      - host:host-gateway
      - init:${ATELIER_SUBNET}.22.1
      - active:${ATELIER_SUBNET}.22.14
      - standby:${ATELIER_SUBNET}.22.44
      - standalone:${ATELIER_SUBNET}.22.74
    networks:
      default:
        ipv4_address: ${ATELIER_SUBNET}.22.44
    volumes:
      - ubuntu22-pg14-standby-vscode-server:/var/lib/postgresql/.vscode-server
      - ubuntu22-pg14-standby-workspace:/var/lib/postgresql/workspace
  ubuntu22-pg14-standalone:
    image: ubuntu22-pg14
    container_name: ubuntu22-pg14-standalone
    hostname: ubuntu22-pg14-standalone
    domainname: atelier
    privileged: true
    tty: false
    extra_hosts:
      - host.docker.internal:host-gateway
      - host:host-gateway
      - init:${ATELIER_SUBNET}.22.1
      - active:${ATELIER_SUBNET}.22.14
      - standby:${ATELIER_SUBNET}.22.44
      - standalone:${ATELIER_SUBNET}.22.74
    networks:
      default:
        ipv4_address: ${ATELIER_SUBNET}.22.74
    volumes:
      - ubuntu22-pg14-standalone-vscode-server:/var/lib/postgresql/.vscode-server
      - ubuntu22-pg14-standalone-workspace:/var/lib/postgresql/workspace
  ubuntu24-init:
    image: ubuntu24-init
    container_name: ubuntu24-init
    hostname: ubuntu24-init
    domainname: atelier
    privileged: true
    tty: false
    extra_hosts:
      - host.docker.internal:host-gateway
      - host:host-gateway
      - init:${ATELIER_SUBNET}.24.1
      - active:${ATELIER_SUBNET}.24.14
      - standby:${ATELIER_SUBNET}.24.44
      - standalone:${ATELIER_SUBNET}.24.74
    networks:
      default:
        ipv4_address: ${ATELIER_SUBNET}.24.1
  ubuntu24-pg14-active:
    image: ubuntu24-pg14
    container_name: ubuntu24-pg14-active
    hostname: ubuntu24-pg14-active
    domainname: atelier
    privileged: true
    tty: false
    extra_hosts:
      - host.docker.internal:host-gateway
      - host:host-gateway
      - init:${ATELIER_SUBNET}.24.1
      - active:${ATELIER_SUBNET}.24.14
      - standby:${ATELIER_SUBNET}.24.44
      - standalone:${ATELIER_SUBNET}.24.74
    networks:
      default:
        ipv4_address: ${ATELIER_SUBNET}.24.14
    volumes:
      - ubuntu24-pg14-active-vscode-server:/var/lib/postgresql/.vscode-server
      - ubuntu24-pg14-active-workspace:/var/lib/postgresql/workspace
  ubuntu24-pg14-standby:
    image: ubuntu24-pg14
    container_name: ubuntu24-pg14-standby
    hostname: ubuntu24-pg14-standby
    domainname: atelier
    privileged: true
    tty: false
    extra_hosts:
      - host.docker.internal:host-gateway
      - host:host-gateway
      - init:${ATELIER_SUBNET}.24.1
      - active:${ATELIER_SUBNET}.24.14
      - standby:${ATELIER_SUBNET}.24.44
      - standalone:${ATELIER_SUBNET}.24.74
    networks:
      default:
        ipv4_address: ${ATELIER_SUBNET}.24.44
    volumes:
      - ubuntu24-pg14-standby-vscode-server:/var/lib/postgresql/.vscode-server
      - ubuntu24-pg14-standby-workspace:/var/lib/postgresql/workspace
  ubuntu24-pg14-standalone:
    image: ubuntu24-pg14
    container_name: ubuntu24-pg14-standalone
    hostname: ubuntu24-pg14-standalone
    domainname: atelier
    privileged: true
    tty: false
    extra_hosts:
      - host.docker.internal:host-gateway
      - host:host-gateway
      - init:${ATELIER_SUBNET}.24.1
      - active:${ATELIER_SUBNET}.24.14
      - standby:${ATELIER_SUBNET}.24.44
      - standalone:${ATELIER_SUBNET}.24.74
    networks:
      default:
        ipv4_address: ${ATELIER_SUBNET}.24.74
    volumes:
      - ubuntu24-pg14-standalone-vscode-server:/var/lib/postgresql/.vscode-server
      - ubuntu24-pg14-standalone-workspace:/var/lib/postgresql/workspace
  haproxy:
    image: haproxy
    container_name: haproxy
    hostname: haproxy
    domainname: atelier
    tty: false
    depends_on:
      - rocky8-init
      - rocky9-init
      - ubuntu22-init
      - ubuntu24-init
    extra_hosts:
      - host.docker.internal:host-gateway
      - host:host-gateway
    networks:
      default:
        ipv4_address: ${ATELIER_SUBNET}.200.1
    volumes:
      - ./volumes/haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    ports:
      - '${ATELIER_SSH_PORT}:8022'
  apache2:
    image: ubuntu/apache2
    container_name: apache2
    hostname: apache2
    domainname: atelier
    tty: false
    extra_hosts:
      - host.docker.internal:host-gateway
      - host:host-gateway
    networks:
      default:
        ipv4_address: ${ATELIER_SUBNET}.200.2
    volumes:
      - ./volumes/apache2/html:/var/www/html
    ports:
      - '${ATELIER_HTTP_PORT}:80'
  squid:
    image: ubuntu/squid
    container_name: squid
    hostname: squid
    domainname: atelier
    tty: false
    extra_hosts:
      - host.docker.internal:host-gateway
      - host:host-gateway
    networks:
      default:
        ipv4_address: ${ATELIER_SUBNET}.200.3
    volumes:
      - ./volumes/squid/squid.conf:/etc/squid/squid.conf:ro
      - squid-logs:/var/log/squid
      - squid-spool:/var/spool/squid
    ports:
      - '${ATELIER_SQUID_PORT}:3128'
networks:
  default:
    name: atelier
    ipam:
      config:
        - subnet: ${ATELIER_SUBNET}.0.0/16
volumes:
  squid-logs:
  squid-spool:
  rocky8-pg14-active-workspace:
  rocky8-pg14-standby-workspace:
  rocky8-pg14-standalone-workspace:
  rocky9-pg14-active-workspace:
  rocky9-pg14-standby-workspace:
  rocky9-pg14-standalone-workspace:
  ubuntu22-pg14-active-workspace:
  ubuntu22-pg14-standby-workspace:
  ubuntu22-pg14-standalone-workspace:
  ubuntu24-pg14-active-workspace:
  ubuntu24-pg14-standby-workspace:
  ubuntu24-pg14-standalone-workspace:
  rocky8-pg14-active-vscode-server:
  rocky8-pg14-standby-vscode-server:
  rocky8-pg14-standalone-vscode-server:
  rocky9-pg14-active-vscode-server:
  rocky9-pg14-standby-vscode-server:
  rocky9-pg14-standalone-vscode-server:
  ubuntu22-pg14-active-vscode-server:
  ubuntu22-pg14-standby-vscode-server:
  ubuntu22-pg14-standalone-vscode-server:
  ubuntu24-pg14-active-vscode-server:
  ubuntu24-pg14-standby-vscode-server:
  ubuntu24-pg14-standalone-vscode-server:
