#!/bin/bash

. ./.env

MAX_RETRY=10
DELAY=10

retry () {
    COUNT=${MAX_RETRY}
    echo "[TRY] $@"
    "$@"
    RESULT=$?
    while [ $RESULT -ne 0 ]; do
        if [ $COUNT -le 0 ]; then
            break
        fi
        COUNT=$(($COUNT - 1))
        sleep $DELAY
        echo "[RETRY] $@"
        "$@"
        RESULT=$?
    done
    if [ $RESULT -eq 0 ]; then
        echo "[SUCCESS] $@"
    else
        echo "[FAILED] $@"
    fi
    return $RESULT
}

docker compose up -d squid && sleep 3

retry docker build --add-host host.docker.internal:host-gateway --build-arg ATELIER_SQUID_PORT="${ATELIER_SQUID_PORT}"                         -t rocky8-init   -f dockerfiles/rocky/8/Dockerfile-init   dockerfiles
retry docker build --add-host host.docker.internal:host-gateway --build-arg ATELIER_SQUID_PORT="${ATELIER_SQUID_PORT}" --build-arg PG_MAJOR=14 -t rocky8-pg14   -f dockerfiles/rocky/8/Dockerfile-pgxx   dockerfiles
retry docker build --add-host host.docker.internal:host-gateway --build-arg ATELIER_SQUID_PORT="${ATELIER_SQUID_PORT}" --build-arg PG_MAJOR=15 -t rocky8-pg15   -f dockerfiles/rocky/8/Dockerfile-pgxx   dockerfiles
retry docker build --add-host host.docker.internal:host-gateway --build-arg ATELIER_SQUID_PORT="${ATELIER_SQUID_PORT}" --build-arg PG_MAJOR=16 -t rocky8-pg16   -f dockerfiles/rocky/8/Dockerfile-pgxx   dockerfiles
retry docker build --add-host host.docker.internal:host-gateway --build-arg ATELIER_SQUID_PORT="${ATELIER_SQUID_PORT}" --build-arg PG_MAJOR=17 -t rocky8-pg17   -f dockerfiles/rocky/8/Dockerfile-pgxx   dockerfiles

retry docker build --add-host host.docker.internal:host-gateway --build-arg ATELIER_SQUID_PORT="${ATELIER_SQUID_PORT}"                         -t rocky9-init   -f dockerfiles/rocky/9/Dockerfile-init   dockerfiles
retry docker build --add-host host.docker.internal:host-gateway --build-arg ATELIER_SQUID_PORT="${ATELIER_SQUID_PORT}" --build-arg PG_MAJOR=14 -t rocky9-pg14   -f dockerfiles/rocky/9/Dockerfile-pgxx   dockerfiles
retry docker build --add-host host.docker.internal:host-gateway --build-arg ATELIER_SQUID_PORT="${ATELIER_SQUID_PORT}" --build-arg PG_MAJOR=15 -t rocky9-pg15   -f dockerfiles/rocky/9/Dockerfile-pgxx   dockerfiles
retry docker build --add-host host.docker.internal:host-gateway --build-arg ATELIER_SQUID_PORT="${ATELIER_SQUID_PORT}" --build-arg PG_MAJOR=16 -t rocky9-pg16   -f dockerfiles/rocky/9/Dockerfile-pgxx   dockerfiles
retry docker build --add-host host.docker.internal:host-gateway --build-arg ATELIER_SQUID_PORT="${ATELIER_SQUID_PORT}" --build-arg PG_MAJOR=17 -t rocky9-pg17   -f dockerfiles/rocky/9/Dockerfile-pgxx   dockerfiles

retry docker build --add-host host.docker.internal:host-gateway --build-arg ATELIER_SQUID_PORT="${ATELIER_SQUID_PORT}"                         -t ubuntu22-init -f dockerfiles/ubuntu/22/Dockerfile-init dockerfiles
retry docker build --add-host host.docker.internal:host-gateway --build-arg ATELIER_SQUID_PORT="${ATELIER_SQUID_PORT}" --build-arg PG_MAJOR=14 -t ubuntu22-pg14 -f dockerfiles/ubuntu/22/Dockerfile-pgxx dockerfiles
retry docker build --add-host host.docker.internal:host-gateway --build-arg ATELIER_SQUID_PORT="${ATELIER_SQUID_PORT}" --build-arg PG_MAJOR=15 -t ubuntu22-pg15 -f dockerfiles/ubuntu/22/Dockerfile-pgxx dockerfiles
retry docker build --add-host host.docker.internal:host-gateway --build-arg ATELIER_SQUID_PORT="${ATELIER_SQUID_PORT}" --build-arg PG_MAJOR=16 -t ubuntu22-pg16 -f dockerfiles/ubuntu/22/Dockerfile-pgxx dockerfiles
retry docker build --add-host host.docker.internal:host-gateway --build-arg ATELIER_SQUID_PORT="${ATELIER_SQUID_PORT}" --build-arg PG_MAJOR=17 -t ubuntu22-pg17 -f dockerfiles/ubuntu/22/Dockerfile-pgxx dockerfiles

retry docker build --add-host host.docker.internal:host-gateway --build-arg ATELIER_SQUID_PORT="${ATELIER_SQUID_PORT}"                         -t ubuntu24-init -f dockerfiles/ubuntu/24/Dockerfile-init dockerfiles
retry docker build --add-host host.docker.internal:host-gateway --build-arg ATELIER_SQUID_PORT="${ATELIER_SQUID_PORT}" --build-arg PG_MAJOR=14 -t ubuntu24-pg14 -f dockerfiles/ubuntu/24/Dockerfile-pgxx dockerfiles
retry docker build --add-host host.docker.internal:host-gateway --build-arg ATELIER_SQUID_PORT="${ATELIER_SQUID_PORT}" --build-arg PG_MAJOR=15 -t ubuntu24-pg15 -f dockerfiles/ubuntu/24/Dockerfile-pgxx dockerfiles
retry docker build --add-host host.docker.internal:host-gateway --build-arg ATELIER_SQUID_PORT="${ATELIER_SQUID_PORT}" --build-arg PG_MAJOR=16 -t ubuntu24-pg16 -f dockerfiles/ubuntu/24/Dockerfile-pgxx dockerfiles
retry docker build --add-host host.docker.internal:host-gateway --build-arg ATELIER_SQUID_PORT="${ATELIER_SQUID_PORT}" --build-arg PG_MAJOR=17 -t ubuntu24-pg17 -f dockerfiles/ubuntu/24/Dockerfile-pgxx dockerfiles
