#!/bin/bash

env="-e IGNOREEOF=99 -e LANG=ko_KR.UTF-8 -e LANGUAGE=ko:en -e LC_ALL=ko_KR.UTF-8"

createSession(){
    tmux has-session -t $1 >/dev/null 2>&1
    if [ $? -ne 0 ]; then
        no=0
        IGNOREEOF=99 tmux new-session -d -s "$1" -n init "docker compose exec -ti $env -w /root rocky9-init /bin/bash --login" \; set -g status-right '"#S:#W.#P" %Y-%m-%d %H:%M:%S#{default}' \; set -g mouse on \; bind -n MouseDown1StatusLeft switch-client -n \; bind -n MouseDown1StatusRight setw synchronize-panes \; bind C-s setw synchronize-panes
        tmux split-window -t "$1:init" "docker compose exec -ti $env -w /root rocky8-init /bin/bash --login" && tmux select-layout -t "$1:init" tiled
        tmux split-window -t "$1:init" "docker compose exec -ti $env -w /root ubuntu24-init /bin/bash --login" && tmux select-layout -t "$1:init" tiled
        tmux split-window -t "$1:init" "docker compose exec -ti $env -w /root ubuntu22-init /bin/bash --login" && tmux select-layout -t "$1:init" tiled
        tmux select-pane -t "$1:init.3"
        let no++
        tmux new-window -t "$1:$no" -n active "docker compose exec -ti $env -w /var/lib/pgsql -u postgres rocky9-pg15-active /bin/bash --login"
        tmux split-window -t "$1:active" "docker compose exec -ti $env -w /var/lib/pgsql -u postgres rocky8-pg15-active /bin/bash --login" && tmux select-layout -t "$1:active" tiled
        tmux split-window -t "$1:active" "docker compose exec -ti $env -w /var/lib/postgresql -u postgres ubuntu24-pg15-active /bin/bash --login" && tmux select-layout -t "$1:active" tiled
        tmux split-window -t "$1:active" "docker compose exec -ti $env -w /var/lib/postgresql -u postgres ubuntu22-pg15-active /bin/bash --login" && tmux select-layout -t "$1:active" tiled
        tmux select-pane -t "$1:active.0"
        let no++
        tmux new-window -t "$1:$no" -n standby "docker compose exec -ti $env -w /var/lib/pgsql -u postgres rocky9-pg15-standby /bin/bash --login"
        tmux split-window -t "$1:standby" "docker compose exec -ti $env -w /var/lib/pgsql -u postgres rocky8-pg15-standby /bin/bash --login" && tmux select-layout -t "$1:standby" tiled
        tmux split-window -t "$1:standby" "docker compose exec -ti $env -w /var/lib/postgresql -u postgres ubuntu24-pg15-standby /bin/bash --login" && tmux select-layout -t "$1:standby" tiled
        tmux split-window -t "$1:standby" "docker compose exec -ti $env -w /var/lib/postgresql -u postgres ubuntu22-pg15-standby /bin/bash --login" && tmux select-layout -t "$1:standby" tiled
        tmux select-pane -t "$1:standby.0"
        let no++
        tmux new-window -t "$1:$no" -n standalone "docker compose exec -ti $env -w /var/lib/pgsql -u postgres rocky9-pg15-standalone /bin/bash --login"
        tmux split-window -t "$1:standalone" "docker compose exec -ti $env -w /var/lib/pgsql -u postgres rocky8-pg15-standalone /bin/bash --login" && tmux select-layout -t "$1:standalone" tiled
        tmux split-window -t "$1:standalone" "docker compose exec -ti $env -w /var/lib/postgresql -u postgres ubuntu24-pg15-standalone /bin/bash --login" && tmux select-layout -t "$1:standalone" tiled
        tmux split-window -t "$1:standalone" "docker compose exec -ti $env -w /var/lib/postgresql -u postgres ubuntu22-pg15-standalone /bin/bash --login" && tmux select-layout -t "$1:standalone" tiled
        tmux select-pane -t "$1:standalone.0"
        let no++
        tmux new-window -t "$1:$no" -n rocky9 "docker compose exec -ti $env -w /var/lib/pgsql -u postgres rocky9-pg15-active /bin/bash --login"
        tmux split-window -t "$1:rocky9" "docker compose exec -ti $env -w /var/lib/pgsql -u postgres rocky9-pg15-standby /bin/bash --login" && tmux select-layout -t "$1:rocky9" tiled
        tmux split-window -t "$1:rocky9" "docker compose exec -ti $env -w /var/lib/pgsql -u postgres rocky9-pg15-standalone /bin/bash --login" && tmux select-layout -t "$1:rocky9" tiled
        tmux select-pane -t "$1:rocky9.0"
        let no++
        tmux new-window -t "$1:$no" -n rocky8 "docker compose exec -ti $env -w /var/lib/pgsql -u postgres rocky8-pg15-active /bin/bash --login"
        tmux split-window -t "$1:rocky8" "docker compose exec -ti $env -w /var/lib/pgsql -u postgres rocky8-pg15-standby /bin/bash --login" && tmux select-layout -t "$1:rocky8" tiled
        tmux split-window -t "$1:rocky8" "docker compose exec -ti $env -w /var/lib/pgsql -u postgres rocky8-pg15-standalone /bin/bash --login" && tmux select-layout -t "$1:rocky8" tiled
        tmux select-pane -t "$1:rocky8.0"
        let no++
        tmux new-window -t "$1:$no" -n ubuntu24 "docker compose exec -ti $env -w /var/lib/postgresql -u postgres ubuntu24-pg15-active /bin/bash --login"
        tmux split-window -t "$1:ubuntu24" "docker compose exec -ti $env -w /var/lib/postgresql -u postgres ubuntu24-pg15-standby /bin/bash --login" && tmux select-layout -t "$1:ubuntu24" tiled
        tmux split-window -t "$1:ubuntu24" "docker compose exec -ti $env -w /var/lib/postgresql -u postgres ubuntu24-pg15-standalone /bin/bash --login" && tmux select-layout -t "$1:ubuntu24" tiled
        tmux select-pane -t "$1:ubuntu24.0"
        let no++
        tmux new-window -t "$1:$no" -n ubuntu22 "docker compose exec -ti $env -w /var/lib/postgresql -u postgres ubuntu22-pg15-active /bin/bash --login"
        tmux split-window -t "$1:ubuntu22" "docker compose exec -ti $env -w /var/lib/postgresql -u postgres ubuntu22-pg15-standby /bin/bash --login" && tmux select-layout -t "$1:ubuntu22" tiled
        tmux split-window -t "$1:ubuntu22" "docker compose exec -ti $env -w /var/lib/postgresql -u postgres ubuntu22-pg15-standalone /bin/bash --login" && tmux select-layout -t "$1:ubuntu22" tiled
        tmux select-pane -t "$1:ubuntu22.0"
        let no++
        tmux new-window -t "$1:$no" -n rocky "docker compose exec -ti $env -w /root rocky9-init /bin/bash --login"
        tmux split-window -t "$1:rocky" "docker compose exec -ti $env -w /root rocky8-init /bin/bash --login" && tmux select-layout -t "$1:rocky" even-horizontal
        let no++
        tmux new-window -t "$1:$no" -n ubuntu "docker compose exec -ti $env -w /root ubuntu24-init /bin/bash --login"
        tmux split-window -t "$1:ubuntu" "docker compose exec -ti $env -w /root ubuntu22-init /bin/bash --login" && tmux select-layout -t "$1:ubuntu" even-horizontal
        let no++
        tmux new-window -t "$1:$no" -n logs "docker compose logs -f haproxy apache2 squid"
        let no++
        tmux new-window -t "$1:$no" -n monitor "bash -c 'while true; do bpytop; done'"
        tmux select-window -t "$1:bpytop"
        tmux select-window -t "$1:init"
    fi
    return 0
}

if [ -z "$TMUX_DETACH" ]; then
    TMUX_DETACH=0
fi

if [ $# -gt 1 ]; then
    for session in $@; do
        createSession "$session"
    done
    if [ "$TMUX_DETACH" -eq 0 ]; then
        exec tmux attach-session -t "$1"
    fi
else
    if [ $# -gt 0 ]; then
        session=$1
    else
        session="docker"
    fi
    createSession "$session"
    if [ "$TMUX_DETACH" -eq 0 ]; then
        exec tmux attach-session -t "$session"
    fi
fi
