#!/bin/bash

env="-e IGNOREEOF=99 -e LANG=ko_KR.UTF-8 -e LANGUAGE=ko:en -e LC_ALL=ko_KR.UTF-8"

createSession(){
    tmux has-session -t "$1" >/dev/null 2>&1
    if [ $? -ne 0 ]; then
        no=0
        IGNOREEOF=99 tmux new-session -d  -x 270 -y 59 -s "$1" -n "builder" "bash -c 'while sleep 1; do bpytop; done'" \; set -g status-right '"#S:#W.#P" %Y-%m-%d %H:%M:%S#{default}' \; set -g mouse on \; bind -n MouseDown1StatusLeft switch-client -n \; bind -n MouseDown1StatusRight setw synchronize-panes \; bind C-s setw synchronize-panes
        tmux split-window -v -t "$1:builder.0" "while sleep 1; do docker compose logs -f haproxy apache2 squid; done"
        tmux split-window -h -t "$1:builder.0" "bash"
        tmux resize-pane -t "$1:builder.0" -x 185 -y 45
    fi
    return 0
}

if [ -z "$TMUX_DETACH" ]; then
    TMUX_DETACH=0
fi

if [ $# -gt 1 ]; then
    for session in $@; do
        createSession "$session"
    done
    if [ "$TMUX_DETACH" -eq 0 ]; then
        exec tmux attach-session -t "$1"
    fi
else
    if [ $# -gt 0 ]; then
        session="$1"
    else
        session="atelier"
    fi
    createSession "$session"
    if [ "$TMUX_DETACH" -eq 0 ]; then
        exec tmux attach-session -t "$session"
    fi
fi
